select
req.request_id, 
req.request_type_name,
req.workflow_name,
req.priority_meaning,
req.creation_date,
req.created_by_name,
(select full_name from knta_users where user_id=req.last_updated_by),
decode(req.status_code,'CLOSED_SUCCESS','Geschlossen', 'CLOSED_FAILURE','Gestoppt','Offen'),
req.status_name,
(select workflow_step_id from knta_pending_workflow_steps_v where instance_source_id=req.request_id and Product_scope_code='RI'),
(select workflow_step from knta_pending_workflow_steps_v where instance_source_id=req.request_id and Product_scope_code='RI'),
req.description,
req.percent_complete,
req.visible_parameter1,
req.visible_parameter2,
req.visible_parameter3,
req.visible_parameter4,
req.visible_parameter5,
req.visible_parameter6,
req.visible_parameter7,
req.visible_parameter8,
req.visible_parameter9,
req.created_by,
req.last_updated_by
from kcrt_requests_v req