//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
// 
#pragma warning disable 1591

namespace DemandServiceTest.localhostDemandService {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DemandServiceSOAP11Binding", Namespace="http://mercury.com/ppm/dm/msg/1.0")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Reference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Field))]
    public partial class DemandServiceWse : Microsoft.Web.Services3.WebServicesClientProtocol {
        
        private System.Threading.SendOrPostCallback setRemoteRequestStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback setRequestRemoteReferenceStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback addRequestNotesOperationCompleted;
        
        private System.Threading.SendOrPostCallback createRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteRequestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback setRequestFieldsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRequestsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DemandServiceWse() {
            this.Url = global::DemandServiceTest.Properties.Settings.Default.DemandServiceTest_localhostDemandService_DemandService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event setRemoteRequestStatusCompletedEventHandler setRemoteRequestStatusCompleted;
        
        /// <remarks/>
        public event setRequestRemoteReferenceStatusCompletedEventHandler setRequestRemoteReferenceStatusCompleted;
        
        /// <remarks/>
        public event addRequestNotesCompletedEventHandler addRequestNotesCompleted;
        
        /// <remarks/>
        public event createRequestCompletedEventHandler createRequestCompleted;
        
        /// <remarks/>
        public event deleteRequestsCompletedEventHandler deleteRequestsCompleted;
        
        /// <remarks/>
        public event setRequestFieldsCompletedEventHandler setRequestFieldsCompleted;
        
        /// <remarks/>
        public event getRequestsCompletedEventHandler getRequestsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setRemoteRequestStatus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void setRemoteRequestStatus() {
            this.Invoke("setRemoteRequestStatus", new object[0]);
        }
        
        /// <remarks/>
        public void setRemoteRequestStatusAsync() {
            this.setRemoteRequestStatusAsync(null);
        }
        
        /// <remarks/>
        public void setRemoteRequestStatusAsync(object userState) {
            if ((this.setRemoteRequestStatusOperationCompleted == null)) {
                this.setRemoteRequestStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetRemoteRequestStatusOperationCompleted);
            }
            this.InvokeAsync("setRemoteRequestStatus", new object[0], this.setRemoteRequestStatusOperationCompleted, userState);
        }
        
        private void OnsetRemoteRequestStatusOperationCompleted(object arg) {
            if ((this.setRemoteRequestStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setRemoteRequestStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setRequestRemoteReferenceStatus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("setRequestRemoteReferenceStatusResponse", Namespace="http://mercury.com/ppm/dm/service/1.0")]
        public setRequestRemoteReferenceStatusResponse setRequestRemoteReferenceStatus([System.Xml.Serialization.XmlElementAttribute("setRequestRemoteReferenceStatus", Namespace="http://mercury.com/ppm/dm/service/1.0")] setRequestRemoteReferenceStatus setRequestRemoteReferenceStatus1) {
            object[] results = this.Invoke("setRequestRemoteReferenceStatus", new object[] {
                        setRequestRemoteReferenceStatus1});
            return ((setRequestRemoteReferenceStatusResponse)(results[0]));
        }
        
        /// <remarks/>
        public void setRequestRemoteReferenceStatusAsync(setRequestRemoteReferenceStatus setRequestRemoteReferenceStatus1) {
            this.setRequestRemoteReferenceStatusAsync(setRequestRemoteReferenceStatus1, null);
        }
        
        /// <remarks/>
        public void setRequestRemoteReferenceStatusAsync(setRequestRemoteReferenceStatus setRequestRemoteReferenceStatus1, object userState) {
            if ((this.setRequestRemoteReferenceStatusOperationCompleted == null)) {
                this.setRequestRemoteReferenceStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetRequestRemoteReferenceStatusOperationCompleted);
            }
            this.InvokeAsync("setRequestRemoteReferenceStatus", new object[] {
                        setRequestRemoteReferenceStatus1}, this.setRequestRemoteReferenceStatusOperationCompleted, userState);
        }
        
        private void OnsetRequestRemoteReferenceStatusOperationCompleted(object arg) {
            if ((this.setRequestRemoteReferenceStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setRequestRemoteReferenceStatusCompleted(this, new setRequestRemoteReferenceStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:addRequestNotes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("addRequestNotesResponse", Namespace="http://mercury.com/ppm/dm/service/1.0")]
        public addRequestNotesResponse addRequestNotes([System.Xml.Serialization.XmlElementAttribute("addRequestNotes", Namespace="http://mercury.com/ppm/dm/service/1.0")] addRequestNotes addRequestNotes1) {
            object[] results = this.Invoke("addRequestNotes", new object[] {
                        addRequestNotes1});
            return ((addRequestNotesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void addRequestNotesAsync(addRequestNotes addRequestNotes1) {
            this.addRequestNotesAsync(addRequestNotes1, null);
        }
        
        /// <remarks/>
        public void addRequestNotesAsync(addRequestNotes addRequestNotes1, object userState) {
            if ((this.addRequestNotesOperationCompleted == null)) {
                this.addRequestNotesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddRequestNotesOperationCompleted);
            }
            this.InvokeAsync("addRequestNotes", new object[] {
                        addRequestNotes1}, this.addRequestNotesOperationCompleted, userState);
        }
        
        private void OnaddRequestNotesOperationCompleted(object arg) {
            if ((this.addRequestNotesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addRequestNotesCompleted(this, new addRequestNotesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:createRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("createRequestResponse", Namespace="http://mercury.com/ppm/dm/service/1.0")]
        public createRequestResponse createRequest([System.Xml.Serialization.XmlElementAttribute("createRequest", Namespace="http://mercury.com/ppm/dm/service/1.0")] createRequest createRequest1) {
            object[] results = this.Invoke("createRequest", new object[] {
                        createRequest1});
            return ((createRequestResponse)(results[0]));
        }
        
        /// <remarks/>
        public void createRequestAsync(createRequest createRequest1) {
            this.createRequestAsync(createRequest1, null);
        }
        
        /// <remarks/>
        public void createRequestAsync(createRequest createRequest1, object userState) {
            if ((this.createRequestOperationCompleted == null)) {
                this.createRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateRequestOperationCompleted);
            }
            this.InvokeAsync("createRequest", new object[] {
                        createRequest1}, this.createRequestOperationCompleted, userState);
        }
        
        private void OncreateRequestOperationCompleted(object arg) {
            if ((this.createRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createRequestCompleted(this, new createRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:deleteRequests", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("deleteRequestsResponse", Namespace="http://mercury.com/ppm/dm/service/1.0")]
        public deleteRequestsResponse deleteRequests([System.Xml.Serialization.XmlArrayAttribute("deleteRequests", Namespace="http://mercury.com/ppm/dm/service/1.0")] [System.Xml.Serialization.XmlArrayItemAttribute("requestIds", IsNullable=false)] Identifier[] deleteRequests1) {
            object[] results = this.Invoke("deleteRequests", new object[] {
                        deleteRequests1});
            return ((deleteRequestsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void deleteRequestsAsync(Identifier[] deleteRequests1) {
            this.deleteRequestsAsync(deleteRequests1, null);
        }
        
        /// <remarks/>
        public void deleteRequestsAsync(Identifier[] deleteRequests1, object userState) {
            if ((this.deleteRequestsOperationCompleted == null)) {
                this.deleteRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteRequestsOperationCompleted);
            }
            this.InvokeAsync("deleteRequests", new object[] {
                        deleteRequests1}, this.deleteRequestsOperationCompleted, userState);
        }
        
        private void OndeleteRequestsOperationCompleted(object arg) {
            if ((this.deleteRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteRequestsCompleted(this, new deleteRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setRequestFields", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("setRequestFieldsResponse", Namespace="http://mercury.com/ppm/dm/service/1.0")]
        public setRequestFieldsResponse setRequestFields([System.Xml.Serialization.XmlElementAttribute("setRequestFields", Namespace="http://mercury.com/ppm/dm/service/1.0")] setRequestFields setRequestFields1) {
            object[] results = this.Invoke("setRequestFields", new object[] {
                        setRequestFields1});
            return ((setRequestFieldsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void setRequestFieldsAsync(setRequestFields setRequestFields1) {
            this.setRequestFieldsAsync(setRequestFields1, null);
        }
        
        /// <remarks/>
        public void setRequestFieldsAsync(setRequestFields setRequestFields1, object userState) {
            if ((this.setRequestFieldsOperationCompleted == null)) {
                this.setRequestFieldsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetRequestFieldsOperationCompleted);
            }
            this.InvokeAsync("setRequestFields", new object[] {
                        setRequestFields1}, this.setRequestFieldsOperationCompleted, userState);
        }
        
        private void OnsetRequestFieldsOperationCompleted(object arg) {
            if ((this.setRequestFieldsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setRequestFieldsCompleted(this, new setRequestFieldsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getRequests", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("getRequestsResponse", Namespace="http://mercury.com/ppm/dm/service/1.0")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("return")]
        public Request[] getRequests([System.Xml.Serialization.XmlArrayAttribute("getRequests", Namespace="http://mercury.com/ppm/dm/service/1.0")] [System.Xml.Serialization.XmlArrayItemAttribute("requestIds")] Identifier[] getRequests1) {
            object[] results = this.Invoke("getRequests", new object[] {
                        getRequests1});
            return ((Request[])(results[0]));
        }
        
        /// <remarks/>
        public void getRequestsAsync(Identifier[] getRequests1) {
            this.getRequestsAsync(getRequests1, null);
        }
        
        /// <remarks/>
        public void getRequestsAsync(Identifier[] getRequests1, object userState) {
            if ((this.getRequestsOperationCompleted == null)) {
                this.getRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRequestsOperationCompleted);
            }
            this.InvokeAsync("getRequests", new object[] {
                        getRequests1}, this.getRequestsOperationCompleted, userState);
        }
        
        private void OngetRequestsOperationCompleted(object arg) {
            if ((this.getRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRequestsCompleted(this, new getRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DemandServiceSOAP11Binding", Namespace="http://mercury.com/ppm/dm/msg/1.0")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Reference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Field))]
    public partial class DemandService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback setRemoteRequestStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback setRequestRemoteReferenceStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback addRequestNotesOperationCompleted;
        
        private System.Threading.SendOrPostCallback createRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteRequestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback setRequestFieldsOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRequestsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DemandService() {
            this.Url = global::DemandServiceTest.Properties.Settings.Default.DemandServiceTest_localhostDemandService_DemandService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event setRemoteRequestStatusCompletedEventHandler setRemoteRequestStatusCompleted;
        
        /// <remarks/>
        public event setRequestRemoteReferenceStatusCompletedEventHandler setRequestRemoteReferenceStatusCompleted;
        
        /// <remarks/>
        public event addRequestNotesCompletedEventHandler addRequestNotesCompleted;
        
        /// <remarks/>
        public event createRequestCompletedEventHandler createRequestCompleted;
        
        /// <remarks/>
        public event deleteRequestsCompletedEventHandler deleteRequestsCompleted;
        
        /// <remarks/>
        public event setRequestFieldsCompletedEventHandler setRequestFieldsCompleted;
        
        /// <remarks/>
        public event getRequestsCompletedEventHandler getRequestsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setRemoteRequestStatus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void setRemoteRequestStatus() {
            this.Invoke("setRemoteRequestStatus", new object[0]);
        }
        
        /// <remarks/>
        public void setRemoteRequestStatusAsync() {
            this.setRemoteRequestStatusAsync(null);
        }
        
        /// <remarks/>
        public void setRemoteRequestStatusAsync(object userState) {
            if ((this.setRemoteRequestStatusOperationCompleted == null)) {
                this.setRemoteRequestStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetRemoteRequestStatusOperationCompleted);
            }
            this.InvokeAsync("setRemoteRequestStatus", new object[0], this.setRemoteRequestStatusOperationCompleted, userState);
        }
        
        private void OnsetRemoteRequestStatusOperationCompleted(object arg) {
            if ((this.setRemoteRequestStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setRemoteRequestStatusCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setRequestRemoteReferenceStatus", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("setRequestRemoteReferenceStatusResponse", Namespace="http://mercury.com/ppm/dm/service/1.0")]
        public setRequestRemoteReferenceStatusResponse setRequestRemoteReferenceStatus([System.Xml.Serialization.XmlElementAttribute("setRequestRemoteReferenceStatus", Namespace="http://mercury.com/ppm/dm/service/1.0")] setRequestRemoteReferenceStatus setRequestRemoteReferenceStatus1) {
            object[] results = this.Invoke("setRequestRemoteReferenceStatus", new object[] {
                        setRequestRemoteReferenceStatus1});
            return ((setRequestRemoteReferenceStatusResponse)(results[0]));
        }
        
        /// <remarks/>
        public void setRequestRemoteReferenceStatusAsync(setRequestRemoteReferenceStatus setRequestRemoteReferenceStatus1) {
            this.setRequestRemoteReferenceStatusAsync(setRequestRemoteReferenceStatus1, null);
        }
        
        /// <remarks/>
        public void setRequestRemoteReferenceStatusAsync(setRequestRemoteReferenceStatus setRequestRemoteReferenceStatus1, object userState) {
            if ((this.setRequestRemoteReferenceStatusOperationCompleted == null)) {
                this.setRequestRemoteReferenceStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetRequestRemoteReferenceStatusOperationCompleted);
            }
            this.InvokeAsync("setRequestRemoteReferenceStatus", new object[] {
                        setRequestRemoteReferenceStatus1}, this.setRequestRemoteReferenceStatusOperationCompleted, userState);
        }
        
        private void OnsetRequestRemoteReferenceStatusOperationCompleted(object arg) {
            if ((this.setRequestRemoteReferenceStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setRequestRemoteReferenceStatusCompleted(this, new setRequestRemoteReferenceStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:addRequestNotes", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("addRequestNotesResponse", Namespace="http://mercury.com/ppm/dm/service/1.0")]
        public addRequestNotesResponse addRequestNotes([System.Xml.Serialization.XmlElementAttribute("addRequestNotes", Namespace="http://mercury.com/ppm/dm/service/1.0")] addRequestNotes addRequestNotes1) {
            object[] results = this.Invoke("addRequestNotes", new object[] {
                        addRequestNotes1});
            return ((addRequestNotesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void addRequestNotesAsync(addRequestNotes addRequestNotes1) {
            this.addRequestNotesAsync(addRequestNotes1, null);
        }
        
        /// <remarks/>
        public void addRequestNotesAsync(addRequestNotes addRequestNotes1, object userState) {
            if ((this.addRequestNotesOperationCompleted == null)) {
                this.addRequestNotesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddRequestNotesOperationCompleted);
            }
            this.InvokeAsync("addRequestNotes", new object[] {
                        addRequestNotes1}, this.addRequestNotesOperationCompleted, userState);
        }
        
        private void OnaddRequestNotesOperationCompleted(object arg) {
            if ((this.addRequestNotesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addRequestNotesCompleted(this, new addRequestNotesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:createRequest", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("createRequestResponse", Namespace="http://mercury.com/ppm/dm/service/1.0")]
        public createRequestResponse createRequest([System.Xml.Serialization.XmlElementAttribute("createRequest", Namespace="http://mercury.com/ppm/dm/service/1.0")] createRequest createRequest1) {
            object[] results = this.Invoke("createRequest", new object[] {
                        createRequest1});
            return ((createRequestResponse)(results[0]));
        }
        
        /// <remarks/>
        public void createRequestAsync(createRequest createRequest1) {
            this.createRequestAsync(createRequest1, null);
        }
        
        /// <remarks/>
        public void createRequestAsync(createRequest createRequest1, object userState) {
            if ((this.createRequestOperationCompleted == null)) {
                this.createRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateRequestOperationCompleted);
            }
            this.InvokeAsync("createRequest", new object[] {
                        createRequest1}, this.createRequestOperationCompleted, userState);
        }
        
        private void OncreateRequestOperationCompleted(object arg) {
            if ((this.createRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createRequestCompleted(this, new createRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:deleteRequests", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("deleteRequestsResponse", Namespace="http://mercury.com/ppm/dm/service/1.0")]
        public deleteRequestsResponse deleteRequests([System.Xml.Serialization.XmlArrayAttribute("deleteRequests", Namespace="http://mercury.com/ppm/dm/service/1.0")] [System.Xml.Serialization.XmlArrayItemAttribute("requestIds", IsNullable=false)] Identifier[] deleteRequests1) {
            object[] results = this.Invoke("deleteRequests", new object[] {
                        deleteRequests1});
            return ((deleteRequestsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void deleteRequestsAsync(Identifier[] deleteRequests1) {
            this.deleteRequestsAsync(deleteRequests1, null);
        }
        
        /// <remarks/>
        public void deleteRequestsAsync(Identifier[] deleteRequests1, object userState) {
            if ((this.deleteRequestsOperationCompleted == null)) {
                this.deleteRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteRequestsOperationCompleted);
            }
            this.InvokeAsync("deleteRequests", new object[] {
                        deleteRequests1}, this.deleteRequestsOperationCompleted, userState);
        }
        
        private void OndeleteRequestsOperationCompleted(object arg) {
            if ((this.deleteRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteRequestsCompleted(this, new deleteRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:setRequestFields", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("setRequestFieldsResponse", Namespace="http://mercury.com/ppm/dm/service/1.0")]
        public setRequestFieldsResponse setRequestFields([System.Xml.Serialization.XmlElementAttribute("setRequestFields", Namespace="http://mercury.com/ppm/dm/service/1.0")] setRequestFields setRequestFields1) {
            object[] results = this.Invoke("setRequestFields", new object[] {
                        setRequestFields1});
            return ((setRequestFieldsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void setRequestFieldsAsync(setRequestFields setRequestFields1) {
            this.setRequestFieldsAsync(setRequestFields1, null);
        }
        
        /// <remarks/>
        public void setRequestFieldsAsync(setRequestFields setRequestFields1, object userState) {
            if ((this.setRequestFieldsOperationCompleted == null)) {
                this.setRequestFieldsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetRequestFieldsOperationCompleted);
            }
            this.InvokeAsync("setRequestFields", new object[] {
                        setRequestFields1}, this.setRequestFieldsOperationCompleted, userState);
        }
        
        private void OnsetRequestFieldsOperationCompleted(object arg) {
            if ((this.setRequestFieldsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setRequestFieldsCompleted(this, new setRequestFieldsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:getRequests", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("getRequestsResponse", Namespace="http://mercury.com/ppm/dm/service/1.0")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("return")]
        public Request[] getRequests([System.Xml.Serialization.XmlArrayAttribute("getRequests", Namespace="http://mercury.com/ppm/dm/service/1.0")] [System.Xml.Serialization.XmlArrayItemAttribute("requestIds")] Identifier[] getRequests1) {
            object[] results = this.Invoke("getRequests", new object[] {
                        getRequests1});
            return ((Request[])(results[0]));
        }
        
        /// <remarks/>
        public void getRequestsAsync(Identifier[] getRequests1) {
            this.getRequestsAsync(getRequests1, null);
        }
        
        /// <remarks/>
        public void getRequestsAsync(Identifier[] getRequests1, object userState) {
            if ((this.getRequestsOperationCompleted == null)) {
                this.getRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRequestsOperationCompleted);
            }
            this.InvokeAsync("getRequests", new object[] {
                        getRequests1}, this.getRequestsOperationCompleted, userState);
        }
        
        private void OngetRequestsOperationCompleted(object arg) {
            if ((this.getRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRequestsCompleted(this, new getRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class setRequestRemoteReferenceStatus {
        
        private Identifier receiverField;
        
        private Identifier sourceField;
        
        private string statusField;
        
        private SimpleField[] fieldsField;
        
        /// <remarks/>
        public Identifier receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
        
        /// <remarks/>
        public Identifier source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fields", IsNullable=true)]
        public SimpleField[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mercury.com/ppm/dm/1.0")]
    public partial class Identifier {
        
        private string idField;
        
        private string serverURLField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string serverURL {
            get {
                return this.serverURLField;
            }
            set {
                this.serverURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(URLReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RemoteReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestRemoteReference))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mercury.com/ppm/dm/1.0")]
    public partial class Reference {
        
        private string addedByField;
        
        private System.Nullable<System.DateTime> creationDateField;
        
        private string descriptionField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string addedBy {
            get {
                return this.addedByField;
            }
            set {
                this.addedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> creationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mercury.com/ppm/dm/1.0")]
    public partial class URLReference : Reference {
        
        private string refURLField;
        
        /// <remarks/>
        public string refURL {
            get {
                return this.refURLField;
            }
            set {
                this.refURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestRemoteReference))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mercury.com/ppm/dm/1.0")]
    public partial class RemoteReference : Reference {
        
        private string displayURLField;
        
        private Identifier identifierField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string displayURL {
            get {
                return this.displayURLField;
            }
            set {
                this.displayURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Identifier identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mercury.com/ppm/dm/1.0")]
    public partial class RequestRemoteReference : RemoteReference {
        
        private string requestTypeNameField;
        
        private string relationTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string requestTypeName {
            get {
                return this.requestTypeNameField;
            }
            set {
                this.requestTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string relationType {
            get {
                return this.relationTypeField;
            }
            set {
                this.relationTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mercury.com/ppm/dm/1.0")]
    public partial class Request {
        
        private string idField;
        
        private string requestTypeField;
        
        private SimpleField[] simpleFieldsField;
        
        private Table[] tablesField;
        
        private Note[] notesField;
        
        private URLReference[] uRLReferencesField;
        
        private RemoteReference[] remoteReferencesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string requestType {
            get {
                return this.requestTypeField;
            }
            set {
                this.requestTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("simpleFields", IsNullable=true)]
        public SimpleField[] simpleFields {
            get {
                return this.simpleFieldsField;
            }
            set {
                this.simpleFieldsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("tables", IsNullable=true)]
        public Table[] tables {
            get {
                return this.tablesField;
            }
            set {
                this.tablesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("notes", IsNullable=true)]
        public Note[] notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("URLReferences", IsNullable=true)]
        public URLReference[] URLReferences {
            get {
                return this.uRLReferencesField;
            }
            set {
                this.uRLReferencesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("remoteReferences", IsNullable=true)]
        public RemoteReference[] remoteReferences {
            get {
                return this.remoteReferencesField;
            }
            set {
                this.remoteReferencesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mercury.com/ppm/dm/1.0")]
    public partial class SimpleField : Field {
        
        private string[] stringValueField;
        
        private System.DateTime dateValueField;
        
        private bool dateValueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stringValue")]
        public string[] stringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dateValue {
            get {
                return this.dateValueField;
            }
            set {
                this.dateValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateValueSpecified {
            get {
                return this.dateValueFieldSpecified;
            }
            set {
                this.dateValueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SimpleField))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Column))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Table))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mercury.com/ppm/common/1.0")]
    public partial class Field {
        
        private string tokenField;
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mercury.com/ppm/common/1.0")]
    public partial class Column : Field {
        
        private string[] valuesField;
        
        private System.Nullable<System.DateTime>[] datesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("values", IsNullable=true)]
        public string[] values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dates", IsNullable=true)]
        public System.Nullable<System.DateTime>[] dates {
            get {
                return this.datesField;
            }
            set {
                this.datesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mercury.com/ppm/common/1.0")]
    public partial class Table : Field {
        
        private Column[] columnsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("columns", IsNullable=true)]
        public Column[] columns {
            get {
                return this.columnsField;
            }
            set {
                this.columnsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FieldChangeNote))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mercury.com/ppm/common/1.0")]
    public partial class Note {
        
        private string authorField;
        
        private System.Nullable<System.DateTime> creationDateField;
        
        private string contentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> creationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://mercury.com/ppm/dm/1.0")]
    public partial class FieldChangeNote : Note {
        
        private string fieldPromptField;
        
        private string oldValueField;
        
        private string newValueField;
        
        /// <remarks/>
        public string fieldPrompt {
            get {
                return this.fieldPromptField;
            }
            set {
                this.fieldPromptField = value;
            }
        }
        
        /// <remarks/>
        public string oldValue {
            get {
                return this.oldValueField;
            }
            set {
                this.oldValueField = value;
            }
        }
        
        /// <remarks/>
        public string newValue {
            get {
                return this.newValueField;
            }
            set {
                this.newValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class setRequestRemoteReferenceStatusResponse {
        
        private System.Nullable<int> returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class addRequestNotes {
        
        private Identifier requestIdField;
        
        private Note[] notesField;
        
        /// <remarks/>
        public Identifier requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("notes")]
        public Note[] notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class addRequestNotesResponse {
        
        private System.Nullable<int> returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class createRequest {
        
        private Request requestObjField;
        
        /// <remarks/>
        public Request requestObj {
            get {
                return this.requestObjField;
            }
            set {
                this.requestObjField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class createRequestResponse {
        
        private RemoteReference returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public RemoteReference @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class deleteRequestsResponse {
        
        private System.Nullable<int> returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class setRequestFields {
        
        private Identifier requestIdField;
        
        private SimpleField[] fieldsField;
        
        /// <remarks/>
        public Identifier requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fields")]
        public SimpleField[] fields {
            get {
                return this.fieldsField;
            }
            set {
                this.fieldsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class setRequestFieldsResponse {
        
        private System.Nullable<int> returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void setRemoteRequestStatusCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void setRequestRemoteReferenceStatusCompletedEventHandler(object sender, setRequestRemoteReferenceStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setRequestRemoteReferenceStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setRequestRemoteReferenceStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public setRequestRemoteReferenceStatusResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((setRequestRemoteReferenceStatusResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void addRequestNotesCompletedEventHandler(object sender, addRequestNotesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addRequestNotesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addRequestNotesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public addRequestNotesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((addRequestNotesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void createRequestCompletedEventHandler(object sender, createRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public createRequestResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((createRequestResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void deleteRequestsCompletedEventHandler(object sender, deleteRequestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public deleteRequestsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((deleteRequestsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void setRequestFieldsCompletedEventHandler(object sender, setRequestFieldsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setRequestFieldsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setRequestFieldsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public setRequestFieldsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((setRequestFieldsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    public delegate void getRequestsCompletedEventHandler(object sender, getRequestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Request[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Request[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591